# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mygui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpBtn.setObjectName("helpBtn")
        self.gridLayout_5.addWidget(self.helpBtn, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 1, 2, 1, 1)
        self.QuitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QuitBtn.setObjectName("QuitBtn")
        self.gridLayout_5.addWidget(self.QuitBtn, 1, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.machIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.machIsentropicRadioButton.setObjectName("machIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.machIsentropicRadioButton, 0, 0, 1, 1)
        self.tempIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.tempIsentropicRadioButton.setObjectName("tempIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.tempIsentropicRadioButton, 1, 0, 1, 1)
        self.pressIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.pressIsentropicRadioButton.setObjectName("pressIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.pressIsentropicRadioButton, 2, 0, 1, 1)
        self.densityIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.densityIsentropicRadioButton.setObjectName("densityIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.densityIsentropicRadioButton, 3, 0, 1, 1)
        self.dynamicIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.dynamicIsentropicRadioButton.setObjectName("dynamicIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.dynamicIsentropicRadioButton, 4, 0, 1, 1)
        self.lowerDynIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.lowerDynIsentropicRadioButton.setObjectName("lowerDynIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.lowerDynIsentropicRadioButton, 5, 0, 1, 1)
        self.greaterDynIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.greaterDynIsentropicRadioButton.setObjectName("greaterDynIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.greaterDynIsentropicRadioButton, 6, 0, 1, 1)
        self.cssIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.cssIsentropicRadioButton.setObjectName("cssIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.cssIsentropicRadioButton, 7, 0, 1, 1)
        self.subAcaIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.subAcaIsentropicRadioButton.setObjectName("subAcaIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.subAcaIsentropicRadioButton, 8, 0, 1, 1)
        self.supAcaIsentropicRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.supAcaIsentropicRadioButton.setObjectName("supAcaIsentropicRadioButton")
        self.gridLayout_6.addWidget(self.supAcaIsentropicRadioButton, 9, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ShowIsentropic = QtWidgets.QTextEdit(self.groupBox_3)
        self.ShowIsentropic.setObjectName("ShowIsentropic")
        self.horizontalLayout.addWidget(self.ShowIsentropic)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 2, 2, 1)
        self.IsentropicBtn = QtWidgets.QPushButton(self.tab_4)
        self.IsentropicBtn.setObjectName("IsentropicBtn")
        self.gridLayout_7.addWidget(self.IsentropicBtn, 1, 0, 1, 1)
        self.ShowIsentropicGraph = QtWidgets.QPushButton(self.tab_4)
        self.ShowIsentropicGraph.setObjectName("ShowIsentropicGraph")
        self.gridLayout_7.addWidget(self.ShowIsentropicGraph, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mach1NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.mach1NormalShockRadioButton.setObjectName("mach1NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.mach1NormalShockRadioButton, 0, 0, 1, 1)
        self.mach2NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.mach2NormalShockRadioButton.setObjectName("mach2NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.mach2NormalShockRadioButton, 1, 0, 1, 1)
        self.P2P1NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.P2P1NormalShockRadioButton.setObjectName("P2P1NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.P2P1NormalShockRadioButton, 2, 0, 1, 1)
        self.densityNormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.densityNormalShockRadioButton.setObjectName("densityNormalShockRadioButton")
        self.gridLayout_9.addWidget(self.densityNormalShockRadioButton, 3, 0, 1, 1)
        self.temperatureNormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.temperatureNormalShockRadioButton.setObjectName("temperatureNormalShockRadioButton")
        self.gridLayout_9.addWidget(self.temperatureNormalShockRadioButton, 4, 0, 1, 1)
        self.p2pt1LowerNormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.p2pt1LowerNormalShockRadioButton.setObjectName("p2pt1LowerNormalShockRadioButton")
        self.gridLayout_9.addWidget(self.p2pt1LowerNormalShockRadioButton, 5, 0, 1, 1)
        self.p2pt1GreaterNormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.p2pt1GreaterNormalShockRadioButton.setObjectName("p2pt1GreaterNormalShockRadioButton")
        self.gridLayout_9.addWidget(self.p2pt1GreaterNormalShockRadioButton, 6, 0, 1, 1)
        self.p2pt2NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.p2pt2NormalShockRadioButton.setObjectName("p2pt2NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.p2pt2NormalShockRadioButton, 7, 0, 1, 1)
        self.pt2pt1NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.pt2pt1NormalShockRadioButton.setObjectName("pt2pt1NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.pt2pt1NormalShockRadioButton, 8, 0, 1, 1)
        self.p1pt2NormalShockRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.p1pt2NormalShockRadioButton.setObjectName("p1pt2NormalShockRadioButton")
        self.gridLayout_9.addWidget(self.p1pt2NormalShockRadioButton, 9, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ShowNormalShock = QtWidgets.QTextEdit(self.groupBox_7)
        self.ShowNormalShock.setObjectName("ShowNormalShock")
        self.gridLayout_8.addWidget(self.ShowNormalShock, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 0, 2, 2, 1)
        self.NormalShockBtn = QtWidgets.QPushButton(self.tab_3)
        self.NormalShockBtn.setObjectName("NormalShockBtn")
        self.gridLayout_10.addWidget(self.NormalShockBtn, 1, 0, 1, 1)
        self.ShowNormalShockGraph = QtWidgets.QPushButton(self.tab_3)
        self.ShowNormalShockGraph.setObjectName("ShowNormalShockGraph")
        self.gridLayout_10.addWidget(self.ShowNormalShockGraph, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ShowObliqueShock = QtWidgets.QTextEdit(self.groupBox_12)
        self.ShowObliqueShock.setObjectName("ShowObliqueShock")
        self.gridLayout_12.addWidget(self.ShowObliqueShock, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_12, 0, 2, 3, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.MxObliqueShockRadioButton = QtWidgets.QRadioButton(self.groupBox_13)
        self.MxObliqueShockRadioButton.setObjectName("MxObliqueShockRadioButton")
        self.gridLayout_13.addWidget(self.MxObliqueShockRadioButton, 0, 0, 1, 1)
        self.saObliqueShockRadioButton = QtWidgets.QRadioButton(self.groupBox_13)
        self.saObliqueShockRadioButton.setObjectName("saObliqueShockRadioButton")
        self.gridLayout_13.addWidget(self.saObliqueShockRadioButton, 1, 0, 1, 1)
        self.wraObliqueShockRadioButton = QtWidgets.QRadioButton(self.groupBox_13)
        self.wraObliqueShockRadioButton.setObjectName("wraObliqueShockRadioButton")
        self.gridLayout_13.addWidget(self.wraObliqueShockRadioButton, 2, 0, 1, 1)
        self.sraObliqueShockRadioButton = QtWidgets.QRadioButton(self.groupBox_13)
        self.sraObliqueShockRadioButton.setObjectName("sraObliqueShockRadioButton")
        self.gridLayout_13.addWidget(self.sraObliqueShockRadioButton, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_13, 0, 0, 1, 2)
        self.ShowObliqueShockGraph = QtWidgets.QPushButton(self.tab_5)
        self.ShowObliqueShockGraph.setObjectName("ShowObliqueShockGraph")
        self.gridLayout_11.addWidget(self.ShowObliqueShockGraph, 2, 1, 1, 1)
        self.ObliqueShockBtn = QtWidgets.QPushButton(self.tab_5)
        self.ObliqueShockBtn.setObjectName("ObliqueShockBtn")
        self.gridLayout_11.addWidget(self.ObliqueShockBtn, 2, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.obliqueBox = QtWidgets.QLineEdit(self.groupBox_14)
        self.obliqueBox.setAlignment(QtCore.Qt.AlignCenter)
        self.obliqueBox.setObjectName("obliqueBox")
        self.gridLayout_14.addWidget(self.obliqueBox, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_14)
        self.label_5.setObjectName("label_5")
        self.gridLayout_14.addWidget(self.label_5, 0, 1, 1, 1)
        self.upstreamObliqueBox = QtWidgets.QLineEdit(self.groupBox_14)
        self.upstreamObliqueBox.setAlignment(QtCore.Qt.AlignCenter)
        self.upstreamObliqueBox.setObjectName("upstreamObliqueBox")
        self.gridLayout_14.addWidget(self.upstreamObliqueBox, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_14)
        self.label_6.setObjectName("label_6")
        self.gridLayout_14.addWidget(self.label_6, 1, 1, 1, 1)
        self.gammaObliqueBox = QtWidgets.QLineEdit(self.groupBox_14)
        self.gammaObliqueBox.setAlignment(QtCore.Qt.AlignCenter)
        self.gammaObliqueBox.setObjectName("gammaObliqueBox")
        self.gridLayout_14.addWidget(self.gammaObliqueBox, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_14)
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 2, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_14, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.machPMradioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.machPMradioButton.setObjectName("machPMradioButton")
        self.gridLayout_16.addWidget(self.machPMradioButton, 0, 0, 1, 1)
        self.pressurePMradioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.pressurePMradioButton.setObjectName("pressurePMradioButton")
        self.gridLayout_16.addWidget(self.pressurePMradioButton, 1, 0, 1, 1)
        self.machAnglePMradioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.machAnglePMradioButton.setObjectName("machAnglePMradioButton")
        self.gridLayout_16.addWidget(self.machAnglePMradioButton, 2, 0, 1, 1)
        self.PMangleRadioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.PMangleRadioButton.setObjectName("PMangleRadioButton")
        self.gridLayout_16.addWidget(self.PMangleRadioButton, 3, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.ShowPM = QtWidgets.QTextEdit(self.groupBox_2)
        self.ShowPM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ShowPM.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ShowPM.setObjectName("ShowPM")
        self.gridLayout_17.addWidget(self.ShowPM, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.PMBtn = QtWidgets.QPushButton(self.tab)
        self.PMBtn.setObjectName("PMBtn")
        self.gridLayout_15.addWidget(self.PMBtn, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.machFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.machFannoRadioButton.setObjectName("machFannoRadioButton")
        self.gridLayout_3.addWidget(self.machFannoRadioButton, 0, 0, 1, 1)
        self.tempFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.tempFannoRadioButton.setObjectName("tempFannoRadioButton")
        self.gridLayout_3.addWidget(self.tempFannoRadioButton, 1, 0, 1, 1)
        self.staticpFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.staticpFannoRadioButton.setObjectName("staticpFannoRadioButton")
        self.gridLayout_3.addWidget(self.staticpFannoRadioButton, 2, 0, 1, 1)
        self.totalLowerFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.totalLowerFannoRadioButton.setObjectName("totalLowerFannoRadioButton")
        self.gridLayout_3.addWidget(self.totalLowerFannoRadioButton, 3, 0, 1, 1)
        self.totalGreaterFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.totalGreaterFannoRadioButton.setObjectName("totalGreaterFannoRadioButton")
        self.gridLayout_3.addWidget(self.totalGreaterFannoRadioButton, 4, 0, 1, 1)
        self.speedFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.speedFannoRadioButton.setObjectName("speedFannoRadioButton")
        self.gridLayout_3.addWidget(self.speedFannoRadioButton, 5, 0, 1, 1)
        self.fldLowerFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.fldLowerFannoRadioButton.setObjectName("fldLowerFannoRadioButton")
        self.gridLayout_3.addWidget(self.fldLowerFannoRadioButton, 6, 0, 1, 1)
        self.fldGreaterFannoRadioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.fldGreaterFannoRadioButton.setObjectName("fldGreaterFannoRadioButton")
        self.gridLayout_3.addWidget(self.fldGreaterFannoRadioButton, 7, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 0, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ShowFanno = QtWidgets.QTextEdit(self.groupBox_9)
        self.ShowFanno.setObjectName("ShowFanno")
        self.gridLayout_2.addWidget(self.ShowFanno, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 0, 2, 2, 1)
        self.FannoBtn = QtWidgets.QPushButton(self.tab_6)
        self.FannoBtn.setObjectName("FannoBtn")
        self.gridLayout.addWidget(self.FannoBtn, 1, 0, 1, 1)
        self.ShowFannoGraph = QtWidgets.QPushButton(self.tab_6)
        self.ShowFannoGraph.setObjectName("ShowFannoGraph")
        self.gridLayout.addWidget(self.ShowFannoGraph, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.machRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.machRayleighRadioButton.setObjectName("machRayleighRadioButton")
        self.gridLayout_19.addWidget(self.machRayleighRadioButton, 0, 0, 1, 1)
        self.totalLowerTempRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.totalLowerTempRayleighRadioButton.setObjectName("totalLowerTempRayleighRadioButton")
        self.gridLayout_19.addWidget(self.totalLowerTempRayleighRadioButton, 1, 0, 1, 1)
        self.totalGreaterTempRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.totalGreaterTempRayleighRadioButton.setObjectName("totalGreaterTempRayleighRadioButton")
        self.gridLayout_19.addWidget(self.totalGreaterTempRayleighRadioButton, 2, 0, 1, 1)
        self.lowerTempRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.lowerTempRayleighRadioButton.setObjectName("lowerTempRayleighRadioButton")
        self.gridLayout_19.addWidget(self.lowerTempRayleighRadioButton, 3, 0, 1, 1)
        self.greaterTempRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.greaterTempRayleighRadioButton.setObjectName("greaterTempRayleighRadioButton")
        self.gridLayout_19.addWidget(self.greaterTempRayleighRadioButton, 4, 0, 1, 1)
        self.pressureRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.pressureRayleighRadioButton.setObjectName("pressureRayleighRadioButton")
        self.gridLayout_19.addWidget(self.pressureRayleighRadioButton, 5, 0, 1, 1)
        self.lowerTotalPressureRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.lowerTotalPressureRayleighRadioButton.setObjectName("lowerTotalPressureRayleighRadioButton")
        self.gridLayout_19.addWidget(self.lowerTotalPressureRayleighRadioButton, 6, 0, 1, 1)
        self.greaterTotalPessureRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.greaterTotalPessureRayleighRadioButton.setObjectName("greaterTotalPessureRayleighRadioButton")
        self.gridLayout_19.addWidget(self.greaterTotalPessureRayleighRadioButton, 7, 0, 1, 1)
        self.speedRayleighRadioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.speedRayleighRadioButton.setObjectName("speedRayleighRadioButton")
        self.gridLayout_19.addWidget(self.speedRayleighRadioButton, 8, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_10, 0, 0, 1, 2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.ShowRayleigh = QtWidgets.QTextEdit(self.groupBox_11)
        self.ShowRayleigh.setObjectName("ShowRayleigh")
        self.gridLayout_20.addWidget(self.ShowRayleigh, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_11, 0, 2, 2, 1)
        self.RayleighBtn = QtWidgets.QPushButton(self.tab_2)
        self.RayleighBtn.setObjectName("RayleighBtn")
        self.gridLayout_18.addWidget(self.RayleighBtn, 1, 0, 1, 1)
        self.ShowRayleighGraph = QtWidgets.QPushButton(self.tab_2)
        self.ShowRayleighGraph.setObjectName("ShowRayleighGraph")
        self.gridLayout_18.addWidget(self.ShowRayleighGraph, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 2, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.incBox = QtWidgets.QLineEdit(self.groupBox)
        self.incBox.setAlignment(QtCore.Qt.AlignCenter)
        self.incBox.setObjectName("incBox")
        self.gridLayout_4.addWidget(self.incBox, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 3, 1, 1)
        self.startBox = QtWidgets.QLineEdit(self.groupBox)
        self.startBox.setAlignment(QtCore.Qt.AlignCenter)
        self.startBox.setObjectName("startBox")
        self.gridLayout_4.addWidget(self.startBox, 0, 0, 1, 1)
        self.endBox = QtWidgets.QLineEdit(self.groupBox)
        self.endBox.setAlignment(QtCore.Qt.AlignCenter)
        self.endBox.setObjectName("endBox")
        self.gridLayout_4.addWidget(self.endBox, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.gammaBox = QtWidgets.QLineEdit(self.groupBox)
        self.gammaBox.setAlignment(QtCore.Qt.AlignCenter)
        self.gammaBox.setObjectName("gammaBox")
        self.gridLayout_4.addWidget(self.gammaBox, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Open_Folder - Default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon2)
        self.actionPrint.setObjectName("actionPrint")
        self.actionDatabase = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabase.setIcon(icon3)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon5)
        self.actionInfo.setObjectName("actionInfo")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionDatabase)
        self.toolBar.addAction(self.actionInfo)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.pushButton.clicked.connect(self.incBox.clear)
        self.pushButton.clicked.connect(self.ShowPM.clear)
        self.pushButton.clicked.connect(self.gammaBox.clear)
        self.pushButton.clicked.connect(self.startBox.clear)
        self.pushButton.clicked.connect(self.endBox.clear)
        self.pushButton.clicked.connect(self.ShowIsentropic.clear)
        self.pushButton.clicked.connect(self.ShowNormalShock.clear)
        self.pushButton.clicked.connect(self.ShowObliqueShock.clear)
        self.pushButton.clicked.connect(self.ShowFanno.clear)
        self.pushButton.clicked.connect(self.ShowRayleigh.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startBox, self.endBox)
        MainWindow.setTabOrder(self.endBox, self.incBox)
        MainWindow.setTabOrder(self.incBox, self.gammaBox)
        MainWindow.setTabOrder(self.gammaBox, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.PMangleRadioButton)
        MainWindow.setTabOrder(self.PMangleRadioButton, self.machPMradioButton)
        MainWindow.setTabOrder(self.machPMradioButton, self.machAnglePMradioButton)
        MainWindow.setTabOrder(self.machAnglePMradioButton, self.QuitBtn)
        MainWindow.setTabOrder(self.QuitBtn, self.pressurePMradioButton)
        MainWindow.setTabOrder(self.pressurePMradioButton, self.ShowPM)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Py_ComFlo"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.pushButton.setText(_translate("MainWindow", "Clear all"))
        self.QuitBtn.setText(_translate("MainWindow", "Quit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parameters"))
        self.machIsentropicRadioButton.setText(_translate("MainWindow", "Mach"))
        self.tempIsentropicRadioButton.setText(_translate("MainWindow", "Temperature ratio, T/Tt"))
        self.pressIsentropicRadioButton.setText(_translate("MainWindow", "Pressure ratio, p/pt"))
        self.densityIsentropicRadioButton.setText(_translate("MainWindow", "Density ratio, ρ/ρt"))
        self.dynamicIsentropicRadioButton.setText(_translate("MainWindow", "Dynamic pressure ratio, q/p"))
        self.lowerDynIsentropicRadioButton.setText(_translate("MainWindow", "Dynamic to total pressure q/pt  M < 1.4"))
        self.greaterDynIsentropicRadioButton.setText(_translate("MainWindow", "Dynamic to total pressure q/pt  M > 1.4"))
        self.cssIsentropicRadioButton.setText(_translate("MainWindow", "Speed of sound ratio, u/a*"))
        self.subAcaIsentropicRadioButton.setText(_translate("MainWindow", "Critical area ratio , A*/A  M < 1"))
        self.supAcaIsentropicRadioButton.setText(_translate("MainWindow", "Critical area ratio , A*/A  M > 1"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.ShowIsentropic.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.IsentropicBtn.setText(_translate("MainWindow", "Calculate"))
        self.ShowIsentropicGraph.setText(_translate("MainWindow", "Show Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Isentropic"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Parameters"))
        self.mach1NormalShockRadioButton.setText(_translate("MainWindow", "Upstream Mach (M1)"))
        self.mach2NormalShockRadioButton.setText(_translate("MainWindow", "Downstream Mach (M2)"))
        self.P2P1NormalShockRadioButton.setText(_translate("MainWindow", "Pressure   p2/p1"))
        self.densityNormalShockRadioButton.setText(_translate("MainWindow", "Density  ρ2/ρ1"))
        self.temperatureNormalShockRadioButton.setText(_translate("MainWindow", "Temperature T2/T1"))
        self.p2pt1LowerNormalShockRadioButton.setText(_translate("MainWindow", "Total pressure  p2/pt1  M < 1.5"))
        self.p2pt1GreaterNormalShockRadioButton.setText(_translate("MainWindow", "Total pressure  p2/pt1  M > 1.5"))
        self.p2pt2NormalShockRadioButton.setText(_translate("MainWindow", "Total pressure  p2/pt2"))
        self.pt2pt1NormalShockRadioButton.setText(_translate("MainWindow", "Total pressure  pt2/pt1"))
        self.p1pt2NormalShockRadioButton.setText(_translate("MainWindow", "Total pressure  p1/pt2"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Output"))
        self.NormalShockBtn.setText(_translate("MainWindow", "Calculate"))
        self.ShowNormalShockGraph.setText(_translate("MainWindow", "Show Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Normal Shock"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Output"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Parameters"))
        self.MxObliqueShockRadioButton.setText(_translate("MainWindow", "Mx"))
        self.saObliqueShockRadioButton.setText(_translate("MainWindow", "Wave angle, ( deg )"))
        self.wraObliqueShockRadioButton.setText(_translate("MainWindow", "Weak ramp angle, ( deg )"))
        self.sraObliqueShockRadioButton.setText(_translate("MainWindow", "Strong ramp angle, ( deg )"))
        self.ShowObliqueShockGraph.setText(_translate("MainWindow", "Show Graph"))
        self.ObliqueShockBtn.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Input"))
        self.label_5.setText(_translate("MainWindow", "Input value of parameter"))
        self.label_6.setText(_translate("MainWindow", "Upstream mach value"))
        self.gammaObliqueBox.setText(_translate("MainWindow", "1.4"))
        self.label_7.setText(_translate("MainWindow", "Gamma (γ) value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Oblique Shock"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Parameters"))
        self.machPMradioButton.setText(_translate("MainWindow", "Mach"))
        self.pressurePMradioButton.setText(_translate("MainWindow", "Pressure, p/pt"))
        self.machAnglePMradioButton.setText(_translate("MainWindow", "Mach angle, μ ( deg )"))
        self.PMangleRadioButton.setText(_translate("MainWindow", "Prandtl-Meyer angle, ν ( deg )"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.PMBtn.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Prandtl - Meyer"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Parameters"))
        self.machFannoRadioButton.setText(_translate("MainWindow", "Mach"))
        self.tempFannoRadioButton.setText(_translate("MainWindow", "Temperature T/T*"))
        self.staticpFannoRadioButton.setText(_translate("MainWindow", "Static pressure p/p*"))
        self.totalLowerFannoRadioButton.setText(_translate("MainWindow", "Total pressure  pt/pt*  M < 1"))
        self.totalGreaterFannoRadioButton.setText(_translate("MainWindow", "Total pressure  pt/pt*  M > 1"))
        self.speedFannoRadioButton.setText(_translate("MainWindow", "Speed ratio u/u*"))
        self.fldLowerFannoRadioButton.setText(_translate("MainWindow", "f (Lcr / D)  M < 1"))
        self.fldGreaterFannoRadioButton.setText(_translate("MainWindow", "f (Lcr / D)  M > 1"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Output"))
        self.FannoBtn.setText(_translate("MainWindow", "Calculate"))
        self.ShowFannoGraph.setText(_translate("MainWindow", "Show Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Fanno"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Parameters"))
        self.machRayleighRadioButton.setText(_translate("MainWindow", "Mach"))
        self.totalLowerTempRayleighRadioButton.setText(_translate("MainWindow", "Total Temperature Tt/Tt* M < 1"))
        self.totalGreaterTempRayleighRadioButton.setText(_translate("MainWindow", "Total Temperature Tt/Tt* M > 1"))
        self.lowerTempRayleighRadioButton.setText(_translate("MainWindow", "Temperature T/T* M < 1"))
        self.greaterTempRayleighRadioButton.setText(_translate("MainWindow", "Temperature T/T* M > 1"))
        self.pressureRayleighRadioButton.setText(_translate("MainWindow", "Pressure p/p*"))
        self.lowerTotalPressureRayleighRadioButton.setText(_translate("MainWindow", "Total pressure pt/pt* M < 1"))
        self.greaterTotalPessureRayleighRadioButton.setText(_translate("MainWindow", "Total pressure pt/pt* M > 1"))
        self.speedRayleighRadioButton.setText(_translate("MainWindow", "Speed ratio u/u*"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Output"))
        self.RayleighBtn.setText(_translate("MainWindow", "Calculate"))
        self.ShowRayleighGraph.setText(_translate("MainWindow", "Show Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Rayleigh"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "Start point"))
        self.incBox.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Increment"))
        self.startBox.setText(_translate("MainWindow", "0"))
        self.endBox.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "End point"))
        self.gammaBox.setText(_translate("MainWindow", "1.4"))
        self.label_4.setText(_translate("MainWindow", "Gamma (γ) value"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Click here to open older file"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open older file "))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Click here to save file"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setToolTip(_translate("MainWindow", "Click here to print"))
        self.actionPrint.setStatusTip(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionDatabase.setText(_translate("MainWindow", "Database"))
        self.actionDatabase.setToolTip(_translate("MainWindow", "Click here to view SQLite3 Database"))
        self.actionDatabase.setStatusTip(_translate("MainWindow", "Enter SQLite3 Database"))
        self.actionDatabase.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Click here to exit Py_ComFlo"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit Py_ComFlo"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionInfo.setToolTip(_translate("MainWindow", "Click here for info "))
        self.actionInfo.setStatusTip(_translate("MainWindow", "Info about Py_ComFlo"))
        self.actionInfo.setShortcut(_translate("MainWindow", "Ctrl+I"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

